name: Stonekaiju2
favicon: null
layout_spectrum: 0.50957
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d081c'
    - '#ffffff'
    - '#1e3cf2'
    - '#b02393'
    - '#85d1f5'
  brandStrength: 0
  lightness: 0.7207174643408507
  saturation: 0
  rhythmicContrast: 0.23528858413919806
purpose: []
