name: Stonekaiju2
favicon: null
layout_spectrum: 0.50593
typography_spectrum: 0.50227
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#413798'
    - '#000100'
    - '#7876fe'
    - '#ff51c0'
  brandStrength: 0.3125
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
