name: Stonekaiju2
favicon: null
layout_spectrum: 0.6359252745751292
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c50103'
    - '#020202'
    - '#68b27a'
    - '#ff797a'
  brandStrength: 0
  lightness: 0.7207174643408507
  saturation: 0.621256115147844
  rhythmicContrast: 0.23528858413919806
purpose: []
